//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int id { get; set; }
        public int AutoId { get; set; }
        public int ClientId { get; set; }
        public double DailyRentalCost { get; set; }
        public System.DateTime RentalStartDate { get; set; }
        public int RentalPeriod { get; set; }
        public double Cost { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Client Client { get; set; }
    }
}
